"""update measure schema

Revision ID: 0b441aca0794
Revises: 4dce176bcc28
Create Date: 2025-01-05 18:25:38.440655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b441aca0794'
down_revision: Union[str, None] = '4dce176bcc28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TABLE measure ALTER COLUMN value TYPE NUMERIC(10, 2) USING value::numeric'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TABLE measure ALTER COLUMN value TYPE VARCHAR USING value::text'
    )
    # ### end Alembic commands ###
