"""user scopes default USER

Revision ID: 4dce176bcc28
Revises: 0cd8b8c49962
Create Date: 2025-01-04 17:15:07.651370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dce176bcc28'
down_revision: Union[str, None] = '0cd8b8c49962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('scopes', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'scopes')
    # ### end Alembic commands ###
