services:
  reef-fast-api:
    build: .
    container_name: reef-fast-api
    ports:
      - 8080:80
    volumes:
      - ./app:/usr/src/app/app
    environment:
      - PYTHONPATH=/usr/src/app
    networks:
      - reef
  database:
    container_name: reef-database
    image: postgres:17
    environment:
      - POSTGRES_DB=reef
      - POSTGRES_PASSWORD=reef
      - POSTGRES_USER=reef
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - reef-data:/var/lib/postgresql/data/pgdata
    networks:
      - reef

volumes:
  reef-data:

networks:
  reef:
    driver: bridge